from enum import Enum


class SegmentationMenuEvents(Enum):
    LOAD_IMAGE = "LOAD_IMAGE"
    SAVE_MASKS_FOR_MULTILAYER_TIFF = "SAVE_MASKS_FOR_MULTILAYER_TIFF"
    SAVE_OUTLINES_FOR_MULTILAYER_TIFF = "SAVE_OUTLINES_FOR_MULTILAYER_TIFF"
    SAVE_MASKS_AND_OUTLINES_FOR_MULTILAYER_TIFF = "SAVE_MASKS_AND_OUTLINES_FOR_MULTILAYER_TIFF"
    SAVE_MASKS_ONLY_NPY = "SAVE_MASKS_ONLY_NPY"
    SAVE_OUTLINES_ONLY_NPY = "SAVE_OUTLINES_NPY"

