from enum import Enum


class DisplayEvents(Enum):
    AUTO_ADJUST_SATURATION_SLIDER = "AUTO_ADJUST_SATURATION_SLIDER"
    CALIBRATED_FOR_CELL_DIAMETER = "CALIBRATED_FOR_CELL_DIAMETER"
    FINISHED_SEGMENTATION = "FINISHED_SEGMENTATION"
    RESET_FOR_NEW_IMAGE = "RESET_FOR_NEW_IMAGE"
    REMOVED_ROI = "REMOVED_ROI"
